# coding: utf-8

"""

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class V1ContainerImage(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, Names=None, SizeBytes=None):
        """
        V1ContainerImage - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'Names': 'list[str]',
            'SizeBytes': 'int'
        }

        self.attribute_map = {
            'Names': 'names',
            'SizeBytes': 'sizeBytes'
        }

        self._Names = Names
        self._SizeBytes = SizeBytes

    @property
    def Names(self):
        """
        Gets the Names of this V1ContainerImage.
        Names by which this image is known. e.g. [\"gcr.io/google_containers/hyperkube:v1.0.7\", \"dockerhub.io/google_containers/hyperkube:v1.0.7\"]

        :return: The Names of this V1ContainerImage.
        :rtype: list[str]
        """
        return self._Names

    @Names.setter
    def Names(self, Names):
        """
        Sets the Names of this V1ContainerImage.
        Names by which this image is known. e.g. [\"gcr.io/google_containers/hyperkube:v1.0.7\", \"dockerhub.io/google_containers/hyperkube:v1.0.7\"]

        :param Names: The Names of this V1ContainerImage.
        :type: list[str]
        """

        self._Names = Names

    @property
    def SizeBytes(self):
        """
        Gets the SizeBytes of this V1ContainerImage.
        The size of the image in bytes.

        :return: The SizeBytes of this V1ContainerImage.
        :rtype: int
        """
        return self._SizeBytes

    @SizeBytes.setter
    def SizeBytes(self, SizeBytes):
        """
        Sets the SizeBytes of this V1ContainerImage.
        The size of the image in bytes.

        :param SizeBytes: The SizeBytes of this V1ContainerImage.
        :type: int
        """

        self._SizeBytes = SizeBytes

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
