# coding: utf-8

"""

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class V1ComponentCondition(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, Type=None, Status=None, Message=None, Error=None):
        """
        V1ComponentCondition - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'Type': 'str',
            'Status': 'str',
            'Message': 'str',
            'Error': 'str'
        }

        self.attribute_map = {
            'Type': 'type',
            'Status': 'status',
            'Message': 'message',
            'Error': 'error'
        }

        self._Type = Type
        self._Status = Status
        self._Message = Message
        self._Error = Error

    @property
    def Type(self):
        """
        Gets the Type of this V1ComponentCondition.
        Type of condition for a component. Valid value: \"Healthy\"

        :return: The Type of this V1ComponentCondition.
        :rtype: str
        """
        return self._Type

    @Type.setter
    def Type(self, Type):
        """
        Sets the Type of this V1ComponentCondition.
        Type of condition for a component. Valid value: \"Healthy\"

        :param Type: The Type of this V1ComponentCondition.
        :type: str
        """

        self._Type = Type

    @property
    def Status(self):
        """
        Gets the Status of this V1ComponentCondition.
        Status of the condition for a component. Valid values for \"Healthy\": \"True\", \"False\", or \"Unknown\".

        :return: The Status of this V1ComponentCondition.
        :rtype: str
        """
        return self._Status

    @Status.setter
    def Status(self, Status):
        """
        Sets the Status of this V1ComponentCondition.
        Status of the condition for a component. Valid values for \"Healthy\": \"True\", \"False\", or \"Unknown\".

        :param Status: The Status of this V1ComponentCondition.
        :type: str
        """

        self._Status = Status

    @property
    def Message(self):
        """
        Gets the Message of this V1ComponentCondition.
        Message about the condition for a component. For example, information about a health check.

        :return: The Message of this V1ComponentCondition.
        :rtype: str
        """
        return self._Message

    @Message.setter
    def Message(self, Message):
        """
        Sets the Message of this V1ComponentCondition.
        Message about the condition for a component. For example, information about a health check.

        :param Message: The Message of this V1ComponentCondition.
        :type: str
        """

        self._Message = Message

    @property
    def Error(self):
        """
        Gets the Error of this V1ComponentCondition.
        Condition error code for a component. For example, a health check error code.

        :return: The Error of this V1ComponentCondition.
        :rtype: str
        """
        return self._Error

    @Error.setter
    def Error(self, Error):
        """
        Sets the Error of this V1ComponentCondition.
        Condition error code for a component. For example, a health check error code.

        :param Error: The Error of this V1ComponentCondition.
        :type: str
        """

        self._Error = Error

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
