# coding: utf-8

"""


    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class V1ContainerStateTerminated(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        V1ContainerStateTerminated - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'exitCode': 'int',
            'signal': 'int',
            'reason': 'str',
            'message': 'str',
            'startedAt': 'datetime',
            'finishedAt': 'datetime',
            'containerID': 'str'
        }

        self.attribute_map = {
            'exitCode': 'exitCode',
            'signal': 'signal',
            'reason': 'reason',
            'message': 'message',
            'startedAt': 'startedAt',
            'finishedAt': 'finishedAt',
            'containerID': 'containerID'
        }


    @property
    def exitCode(self):
        """
        Gets the exitCode of this V1ContainerStateTerminated.
        Exit status from the last termination of the container

        :return: The exitCode of this V1ContainerStateTerminated.
        :rtype: int
        """
        return self._exitCode

    @exitCode.setter
    def exitCode(self, exitCode):
        """
        Sets the exitCode of this V1ContainerStateTerminated.
        Exit status from the last termination of the container

        :param exitCode: The exitCode of this V1ContainerStateTerminated.
        :type: int
        """

        self._exitCode = exitCode

    @property
    def signal(self):
        """
        Gets the signal of this V1ContainerStateTerminated.
        Signal from the last termination of the container

        :return: The signal of this V1ContainerStateTerminated.
        :rtype: int
        """
        return self._signal

    @signal.setter
    def signal(self, signal):
        """
        Sets the signal of this V1ContainerStateTerminated.
        Signal from the last termination of the container

        :param signal: The signal of this V1ContainerStateTerminated.
        :type: int
        """

        self._signal = signal

    @property
    def reason(self):
        """
        Gets the reason of this V1ContainerStateTerminated.
        (brief) reason from the last termination of the container

        :return: The reason of this V1ContainerStateTerminated.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """
        Sets the reason of this V1ContainerStateTerminated.
        (brief) reason from the last termination of the container

        :param reason: The reason of this V1ContainerStateTerminated.
        :type: str
        """

        self._reason = reason

    @property
    def message(self):
        """
        Gets the message of this V1ContainerStateTerminated.
        Message regarding the last termination of the container

        :return: The message of this V1ContainerStateTerminated.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """
        Sets the message of this V1ContainerStateTerminated.
        Message regarding the last termination of the container

        :param message: The message of this V1ContainerStateTerminated.
        :type: str
        """

        self._message = message

    @property
    def startedAt(self):
        """
        Gets the startedAt of this V1ContainerStateTerminated.
        Time at which previous execution of the container started

        :return: The startedAt of this V1ContainerStateTerminated.
        :rtype: datetime
        """
        return self._startedAt

    @startedAt.setter
    def startedAt(self, startedAt):
        """
        Sets the startedAt of this V1ContainerStateTerminated.
        Time at which previous execution of the container started

        :param startedAt: The startedAt of this V1ContainerStateTerminated.
        :type: datetime
        """

        self._startedAt = startedAt

    @property
    def finishedAt(self):
        """
        Gets the finishedAt of this V1ContainerStateTerminated.
        Time at which the container last terminated

        :return: The finishedAt of this V1ContainerStateTerminated.
        :rtype: datetime
        """
        return self._finishedAt

    @finishedAt.setter
    def finishedAt(self, finishedAt):
        """
        Sets the finishedAt of this V1ContainerStateTerminated.
        Time at which the container last terminated

        :param finishedAt: The finishedAt of this V1ContainerStateTerminated.
        :type: datetime
        """

        self._finishedAt = finishedAt

    @property
    def containerID(self):
        """
        Gets the containerID of this V1ContainerStateTerminated.
        Container's ID in the format 'docker://<container_id>'

        :return: The containerID of this V1ContainerStateTerminated.
        :rtype: str
        """
        return self._containerID

    @containerID.setter
    def containerID(self, containerID):
        """
        Sets the containerID of this V1ContainerStateTerminated.
        Container's ID in the format 'docker://<container_id>'

        :param containerID: The containerID of this V1ContainerStateTerminated.
        :type: str
        """

        self._containerID = containerID

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
