# coding: utf-8

"""

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class V1EndpointSubset(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, Addresses=None, NotReadyAddresses=None, Ports=None):
        """
        V1EndpointSubset - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'Addresses': 'list[V1EndpointAddress]',
            'NotReadyAddresses': 'list[V1EndpointAddress]',
            'Ports': 'list[V1EndpointPort]'
        }

        self.attribute_map = {
            'Addresses': 'addresses',
            'NotReadyAddresses': 'notReadyAddresses',
            'Ports': 'ports'
        }

        self._Addresses = Addresses
        self._NotReadyAddresses = NotReadyAddresses
        self._Ports = Ports

    @property
    def Addresses(self):
        """
        Gets the Addresses of this V1EndpointSubset.
        IP addresses which offer the related ports that are marked as ready. These endpoints should be considered safe for load balancers and clients to utilize.

        :return: The Addresses of this V1EndpointSubset.
        :rtype: list[V1EndpointAddress]
        """
        return self._Addresses

    @Addresses.setter
    def Addresses(self, Addresses):
        """
        Sets the Addresses of this V1EndpointSubset.
        IP addresses which offer the related ports that are marked as ready. These endpoints should be considered safe for load balancers and clients to utilize.

        :param Addresses: The Addresses of this V1EndpointSubset.
        :type: list[V1EndpointAddress]
        """

        self._Addresses = Addresses

    @property
    def NotReadyAddresses(self):
        """
        Gets the NotReadyAddresses of this V1EndpointSubset.
        IP addresses which offer the related ports but are not currently marked as ready because they have not yet finished starting, have recently failed a readiness check, or have recently failed a liveness check.

        :return: The NotReadyAddresses of this V1EndpointSubset.
        :rtype: list[V1EndpointAddress]
        """
        return self._NotReadyAddresses

    @NotReadyAddresses.setter
    def NotReadyAddresses(self, NotReadyAddresses):
        """
        Sets the NotReadyAddresses of this V1EndpointSubset.
        IP addresses which offer the related ports but are not currently marked as ready because they have not yet finished starting, have recently failed a readiness check, or have recently failed a liveness check.

        :param NotReadyAddresses: The NotReadyAddresses of this V1EndpointSubset.
        :type: list[V1EndpointAddress]
        """

        self._NotReadyAddresses = NotReadyAddresses

    @property
    def Ports(self):
        """
        Gets the Ports of this V1EndpointSubset.
        Port numbers available on the related IP addresses.

        :return: The Ports of this V1EndpointSubset.
        :rtype: list[V1EndpointPort]
        """
        return self._Ports

    @Ports.setter
    def Ports(self, Ports):
        """
        Sets the Ports of this V1EndpointSubset.
        Port numbers available on the related IP addresses.

        :param Ports: The Ports of this V1EndpointSubset.
        :type: list[V1EndpointPort]
        """

        self._Ports = Ports

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
