# coding: utf-8

"""

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class V1EndpointPort(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, Name=None, Port=None, Protocol=None):
        """
        V1EndpointPort - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'Name': 'str',
            'Port': 'int',
            'Protocol': 'str'
        }

        self.attribute_map = {
            'Name': 'name',
            'Port': 'port',
            'Protocol': 'protocol'
        }

        self._Name = Name
        self._Port = Port
        self._Protocol = Protocol

    @property
    def Name(self):
        """
        Gets the Name of this V1EndpointPort.
        The name of this port (corresponds to ServicePort.Name). Must be a DNS_LABEL. Optional only if one port is defined.

        :return: The Name of this V1EndpointPort.
        :rtype: str
        """
        return self._Name

    @Name.setter
    def Name(self, Name):
        """
        Sets the Name of this V1EndpointPort.
        The name of this port (corresponds to ServicePort.Name). Must be a DNS_LABEL. Optional only if one port is defined.

        :param Name: The Name of this V1EndpointPort.
        :type: str
        """

        self._Name = Name

    @property
    def Port(self):
        """
        Gets the Port of this V1EndpointPort.
        The port number of the endpoint.

        :return: The Port of this V1EndpointPort.
        :rtype: int
        """
        return self._Port

    @Port.setter
    def Port(self, Port):
        """
        Sets the Port of this V1EndpointPort.
        The port number of the endpoint.

        :param Port: The Port of this V1EndpointPort.
        :type: int
        """

        self._Port = Port

    @property
    def Protocol(self):
        """
        Gets the Protocol of this V1EndpointPort.
        The IP protocol for this port. Must be UDP or TCP. Default is TCP.

        :return: The Protocol of this V1EndpointPort.
        :rtype: str
        """
        return self._Protocol

    @Protocol.setter
    def Protocol(self, Protocol):
        """
        Sets the Protocol of this V1EndpointPort.
        The IP protocol for this port. Must be UDP or TCP. Default is TCP.

        :param Protocol: The Protocol of this V1EndpointPort.
        :type: str
        """

        self._Protocol = Protocol

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
