# coding: utf-8

"""

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class V1NodeStatus(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, Capacity=None, Allocatable=None, Phase=None, Conditions=None, Addresses=None, DaemonEndpoints=None, NodeInfo=None, Images=None, VolumesInUse=None, VolumesAttached=None):
        """
        V1NodeStatus - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'Capacity': 'object',
            'Allocatable': 'object',
            'Phase': 'str',
            'Conditions': 'list[V1NodeCondition]',
            'Addresses': 'list[V1NodeAddress]',
            'DaemonEndpoints': 'V1NodeDaemonEndpoints',
            'NodeInfo': 'V1NodeSystemInfo',
            'Images': 'list[V1ContainerImage]',
            'VolumesInUse': 'list[V1UniqueVolumeName]',
            'VolumesAttached': 'list[V1AttachedVolume]'
        }

        self.attribute_map = {
            'Capacity': 'capacity',
            'Allocatable': 'allocatable',
            'Phase': 'phase',
            'Conditions': 'conditions',
            'Addresses': 'addresses',
            'DaemonEndpoints': 'daemonEndpoints',
            'NodeInfo': 'nodeInfo',
            'Images': 'images',
            'VolumesInUse': 'volumesInUse',
            'VolumesAttached': 'volumesAttached'
        }

        self._Capacity = Capacity
        self._Allocatable = Allocatable
        self._Phase = Phase
        self._Conditions = Conditions
        self._Addresses = Addresses
        self._DaemonEndpoints = DaemonEndpoints
        self._NodeInfo = NodeInfo
        self._Images = Images
        self._VolumesInUse = VolumesInUse
        self._VolumesAttached = VolumesAttached

    @property
    def Capacity(self):
        """
        Gets the Capacity of this V1NodeStatus.
        Capacity represents the total resources of a node. More info: http://releases.k8s.io/HEAD/docs/user-guide/persistent-volumes.md#capacity for more details.

        :return: The Capacity of this V1NodeStatus.
        :rtype: object
        """
        return self._Capacity

    @Capacity.setter
    def Capacity(self, Capacity):
        """
        Sets the Capacity of this V1NodeStatus.
        Capacity represents the total resources of a node. More info: http://releases.k8s.io/HEAD/docs/user-guide/persistent-volumes.md#capacity for more details.

        :param Capacity: The Capacity of this V1NodeStatus.
        :type: object
        """

        self._Capacity = Capacity

    @property
    def Allocatable(self):
        """
        Gets the Allocatable of this V1NodeStatus.
        Allocatable represents the resources of a node that are available for scheduling. Defaults to Capacity.

        :return: The Allocatable of this V1NodeStatus.
        :rtype: object
        """
        return self._Allocatable

    @Allocatable.setter
    def Allocatable(self, Allocatable):
        """
        Sets the Allocatable of this V1NodeStatus.
        Allocatable represents the resources of a node that are available for scheduling. Defaults to Capacity.

        :param Allocatable: The Allocatable of this V1NodeStatus.
        :type: object
        """

        self._Allocatable = Allocatable

    @property
    def Phase(self):
        """
        Gets the Phase of this V1NodeStatus.
        NodePhase is the recently observed lifecycle phase of the node. More info: http://releases.k8s.io/HEAD/docs/admin/node.md#node-phase

        :return: The Phase of this V1NodeStatus.
        :rtype: str
        """
        return self._Phase

    @Phase.setter
    def Phase(self, Phase):
        """
        Sets the Phase of this V1NodeStatus.
        NodePhase is the recently observed lifecycle phase of the node. More info: http://releases.k8s.io/HEAD/docs/admin/node.md#node-phase

        :param Phase: The Phase of this V1NodeStatus.
        :type: str
        """

        self._Phase = Phase

    @property
    def Conditions(self):
        """
        Gets the Conditions of this V1NodeStatus.
        Conditions is an array of current observed node conditions. More info: http://releases.k8s.io/HEAD/docs/admin/node.md#node-condition

        :return: The Conditions of this V1NodeStatus.
        :rtype: list[V1NodeCondition]
        """
        return self._Conditions

    @Conditions.setter
    def Conditions(self, Conditions):
        """
        Sets the Conditions of this V1NodeStatus.
        Conditions is an array of current observed node conditions. More info: http://releases.k8s.io/HEAD/docs/admin/node.md#node-condition

        :param Conditions: The Conditions of this V1NodeStatus.
        :type: list[V1NodeCondition]
        """

        self._Conditions = Conditions

    @property
    def Addresses(self):
        """
        Gets the Addresses of this V1NodeStatus.
        List of addresses reachable to the node. Queried from cloud provider, if available. More info: http://releases.k8s.io/HEAD/docs/admin/node.md#node-addresses

        :return: The Addresses of this V1NodeStatus.
        :rtype: list[V1NodeAddress]
        """
        return self._Addresses

    @Addresses.setter
    def Addresses(self, Addresses):
        """
        Sets the Addresses of this V1NodeStatus.
        List of addresses reachable to the node. Queried from cloud provider, if available. More info: http://releases.k8s.io/HEAD/docs/admin/node.md#node-addresses

        :param Addresses: The Addresses of this V1NodeStatus.
        :type: list[V1NodeAddress]
        """

        self._Addresses = Addresses

    @property
    def DaemonEndpoints(self):
        """
        Gets the DaemonEndpoints of this V1NodeStatus.
        Endpoints of daemons running on the Node.

        :return: The DaemonEndpoints of this V1NodeStatus.
        :rtype: V1NodeDaemonEndpoints
        """
        return self._DaemonEndpoints

    @DaemonEndpoints.setter
    def DaemonEndpoints(self, DaemonEndpoints):
        """
        Sets the DaemonEndpoints of this V1NodeStatus.
        Endpoints of daemons running on the Node.

        :param DaemonEndpoints: The DaemonEndpoints of this V1NodeStatus.
        :type: V1NodeDaemonEndpoints
        """

        self._DaemonEndpoints = DaemonEndpoints

    @property
    def NodeInfo(self):
        """
        Gets the NodeInfo of this V1NodeStatus.
        Set of ids/uuids to uniquely identify the node. More info: http://releases.k8s.io/HEAD/docs/admin/node.md#node-info

        :return: The NodeInfo of this V1NodeStatus.
        :rtype: V1NodeSystemInfo
        """
        return self._NodeInfo

    @NodeInfo.setter
    def NodeInfo(self, NodeInfo):
        """
        Sets the NodeInfo of this V1NodeStatus.
        Set of ids/uuids to uniquely identify the node. More info: http://releases.k8s.io/HEAD/docs/admin/node.md#node-info

        :param NodeInfo: The NodeInfo of this V1NodeStatus.
        :type: V1NodeSystemInfo
        """

        self._NodeInfo = NodeInfo

    @property
    def Images(self):
        """
        Gets the Images of this V1NodeStatus.
        List of container images on this node

        :return: The Images of this V1NodeStatus.
        :rtype: list[V1ContainerImage]
        """
        return self._Images

    @Images.setter
    def Images(self, Images):
        """
        Sets the Images of this V1NodeStatus.
        List of container images on this node

        :param Images: The Images of this V1NodeStatus.
        :type: list[V1ContainerImage]
        """

        self._Images = Images

    @property
    def VolumesInUse(self):
        """
        Gets the VolumesInUse of this V1NodeStatus.
        List of attachable volumes in use (mounted) by the node.

        :return: The VolumesInUse of this V1NodeStatus.
        :rtype: list[V1UniqueVolumeName]
        """
        return self._VolumesInUse

    @VolumesInUse.setter
    def VolumesInUse(self, VolumesInUse):
        """
        Sets the VolumesInUse of this V1NodeStatus.
        List of attachable volumes in use (mounted) by the node.

        :param VolumesInUse: The VolumesInUse of this V1NodeStatus.
        :type: list[V1UniqueVolumeName]
        """

        self._VolumesInUse = VolumesInUse

    @property
    def VolumesAttached(self):
        """
        Gets the VolumesAttached of this V1NodeStatus.
        List of volumes that are attached to the node.

        :return: The VolumesAttached of this V1NodeStatus.
        :rtype: list[V1AttachedVolume]
        """
        return self._VolumesAttached

    @VolumesAttached.setter
    def VolumesAttached(self, VolumesAttached):
        """
        Sets the VolumesAttached of this V1NodeStatus.
        List of volumes that are attached to the node.

        :param VolumesAttached: The VolumesAttached of this V1NodeStatus.
        :type: list[V1AttachedVolume]
        """

        self._VolumesAttached = VolumesAttached

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
