# coding: utf-8

"""


    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class V1NodeSpec(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        V1NodeSpec - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'podCIDR': 'str',
            'externalID': 'str',
            'providerID': 'str',
            'unschedulable': 'bool'
        }

        self.attribute_map = {
            'podCIDR': 'podCIDR',
            'externalID': 'externalID',
            'providerID': 'providerID',
            'unschedulable': 'unschedulable'
        }


    @property
    def podCIDR(self):
        """
        Gets the podCIDR of this V1NodeSpec.
        PodCIDR represents the pod IP range assigned to the node.

        :return: The podCIDR of this V1NodeSpec.
        :rtype: str
        """
        return self._podCIDR

    @podCIDR.setter
    def podCIDR(self, podCIDR):
        """
        Sets the podCIDR of this V1NodeSpec.
        PodCIDR represents the pod IP range assigned to the node.

        :param podCIDR: The podCIDR of this V1NodeSpec.
        :type: str
        """

        self._podCIDR = podCIDR

    @property
    def externalID(self):
        """
        Gets the externalID of this V1NodeSpec.
        External ID of the node assigned by some machine database (e.g. a cloud provider). Deprecated.

        :return: The externalID of this V1NodeSpec.
        :rtype: str
        """
        return self._externalID

    @externalID.setter
    def externalID(self, externalID):
        """
        Sets the externalID of this V1NodeSpec.
        External ID of the node assigned by some machine database (e.g. a cloud provider). Deprecated.

        :param externalID: The externalID of this V1NodeSpec.
        :type: str
        """

        self._externalID = externalID

    @property
    def providerID(self):
        """
        Gets the providerID of this V1NodeSpec.
        ID of the node assigned by the cloud provider in the format: <ProviderName>://<ProviderSpecificNodeID>

        :return: The providerID of this V1NodeSpec.
        :rtype: str
        """
        return self._providerID

    @providerID.setter
    def providerID(self, providerID):
        """
        Sets the providerID of this V1NodeSpec.
        ID of the node assigned by the cloud provider in the format: <ProviderName>://<ProviderSpecificNodeID>

        :param providerID: The providerID of this V1NodeSpec.
        :type: str
        """

        self._providerID = providerID

    @property
    def unschedulable(self):
        """
        Gets the unschedulable of this V1NodeSpec.
        Unschedulable controls node schedulability of new pods. By default, node is schedulable. More info: http://releases.k8s.io/HEAD/docs/admin/node.md#manual-node-administration\"`

        :return: The unschedulable of this V1NodeSpec.
        :rtype: bool
        """
        return self._unschedulable

    @unschedulable.setter
    def unschedulable(self, unschedulable):
        """
        Sets the unschedulable of this V1NodeSpec.
        Unschedulable controls node schedulability of new pods. By default, node is schedulable. More info: http://releases.k8s.io/HEAD/docs/admin/node.md#manual-node-administration\"`

        :param unschedulable: The unschedulable of this V1NodeSpec.
        :type: bool
        """

        self._unschedulable = unschedulable

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
