# coding: utf-8

"""

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class V1PersistentVolumeSpec(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, Capacity=None, GcePersistentDisk=None, AwsElasticBlockStore=None, HostPath=None, Glusterfs=None, Nfs=None, Rbd=None, Iscsi=None, Cinder=None, Cephfs=None, Fc=None, Flocker=None, FlexVolume=None, AzureFile=None, VsphereVolume=None, AccessModes=None, ClaimRef=None, PersistentVolumeReclaimPolicy=None):
        """
        V1PersistentVolumeSpec - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'Capacity': 'object',
            'GcePersistentDisk': 'V1GCEPersistentDiskVolumeSource',
            'AwsElasticBlockStore': 'V1AWSElasticBlockStoreVolumeSource',
            'HostPath': 'V1HostPathVolumeSource',
            'Glusterfs': 'V1GlusterfsVolumeSource',
            'Nfs': 'V1NFSVolumeSource',
            'Rbd': 'V1RBDVolumeSource',
            'Iscsi': 'V1ISCSIVolumeSource',
            'Cinder': 'V1CinderVolumeSource',
            'Cephfs': 'V1CephFSVolumeSource',
            'Fc': 'V1FCVolumeSource',
            'Flocker': 'V1FlockerVolumeSource',
            'FlexVolume': 'V1FlexVolumeSource',
            'AzureFile': 'V1AzureFileVolumeSource',
            'VsphereVolume': 'V1VsphereVirtualDiskVolumeSource',
            'AccessModes': 'list[V1PersistentVolumeAccessMode]',
            'ClaimRef': 'V1ObjectReference',
            'PersistentVolumeReclaimPolicy': 'str'
        }

        self.attribute_map = {
            'Capacity': 'capacity',
            'GcePersistentDisk': 'gcePersistentDisk',
            'AwsElasticBlockStore': 'awsElasticBlockStore',
            'HostPath': 'hostPath',
            'Glusterfs': 'glusterfs',
            'Nfs': 'nfs',
            'Rbd': 'rbd',
            'Iscsi': 'iscsi',
            'Cinder': 'cinder',
            'Cephfs': 'cephfs',
            'Fc': 'fc',
            'Flocker': 'flocker',
            'FlexVolume': 'flexVolume',
            'AzureFile': 'azureFile',
            'VsphereVolume': 'vsphereVolume',
            'AccessModes': 'accessModes',
            'ClaimRef': 'claimRef',
            'PersistentVolumeReclaimPolicy': 'persistentVolumeReclaimPolicy'
        }

        self._Capacity = Capacity
        self._GcePersistentDisk = GcePersistentDisk
        self._AwsElasticBlockStore = AwsElasticBlockStore
        self._HostPath = HostPath
        self._Glusterfs = Glusterfs
        self._Nfs = Nfs
        self._Rbd = Rbd
        self._Iscsi = Iscsi
        self._Cinder = Cinder
        self._Cephfs = Cephfs
        self._Fc = Fc
        self._Flocker = Flocker
        self._FlexVolume = FlexVolume
        self._AzureFile = AzureFile
        self._VsphereVolume = VsphereVolume
        self._AccessModes = AccessModes
        self._ClaimRef = ClaimRef
        self._PersistentVolumeReclaimPolicy = PersistentVolumeReclaimPolicy

    @property
    def Capacity(self):
        """
        Gets the Capacity of this V1PersistentVolumeSpec.
        A description of the persistent volume's resources and capacity. More info: http://releases.k8s.io/HEAD/docs/user-guide/persistent-volumes.md#capacity

        :return: The Capacity of this V1PersistentVolumeSpec.
        :rtype: object
        """
        return self._Capacity

    @Capacity.setter
    def Capacity(self, Capacity):
        """
        Sets the Capacity of this V1PersistentVolumeSpec.
        A description of the persistent volume's resources and capacity. More info: http://releases.k8s.io/HEAD/docs/user-guide/persistent-volumes.md#capacity

        :param Capacity: The Capacity of this V1PersistentVolumeSpec.
        :type: object
        """

        self._Capacity = Capacity

    @property
    def GcePersistentDisk(self):
        """
        Gets the GcePersistentDisk of this V1PersistentVolumeSpec.
        GCEPersistentDisk represents a GCE Disk resource that is attached to a kubelet's host machine and then exposed to the pod. Provisioned by an admin. More info: http://releases.k8s.io/HEAD/docs/user-guide/volumes.md#gcepersistentdisk

        :return: The GcePersistentDisk of this V1PersistentVolumeSpec.
        :rtype: V1GCEPersistentDiskVolumeSource
        """
        return self._GcePersistentDisk

    @GcePersistentDisk.setter
    def GcePersistentDisk(self, GcePersistentDisk):
        """
        Sets the GcePersistentDisk of this V1PersistentVolumeSpec.
        GCEPersistentDisk represents a GCE Disk resource that is attached to a kubelet's host machine and then exposed to the pod. Provisioned by an admin. More info: http://releases.k8s.io/HEAD/docs/user-guide/volumes.md#gcepersistentdisk

        :param GcePersistentDisk: The GcePersistentDisk of this V1PersistentVolumeSpec.
        :type: V1GCEPersistentDiskVolumeSource
        """

        self._GcePersistentDisk = GcePersistentDisk

    @property
    def AwsElasticBlockStore(self):
        """
        Gets the AwsElasticBlockStore of this V1PersistentVolumeSpec.
        AWSElasticBlockStore represents an AWS Disk resource that is attached to a kubelet's host machine and then exposed to the pod. More info: http://releases.k8s.io/HEAD/docs/user-guide/volumes.md#awselasticblockstore

        :return: The AwsElasticBlockStore of this V1PersistentVolumeSpec.
        :rtype: V1AWSElasticBlockStoreVolumeSource
        """
        return self._AwsElasticBlockStore

    @AwsElasticBlockStore.setter
    def AwsElasticBlockStore(self, AwsElasticBlockStore):
        """
        Sets the AwsElasticBlockStore of this V1PersistentVolumeSpec.
        AWSElasticBlockStore represents an AWS Disk resource that is attached to a kubelet's host machine and then exposed to the pod. More info: http://releases.k8s.io/HEAD/docs/user-guide/volumes.md#awselasticblockstore

        :param AwsElasticBlockStore: The AwsElasticBlockStore of this V1PersistentVolumeSpec.
        :type: V1AWSElasticBlockStoreVolumeSource
        """

        self._AwsElasticBlockStore = AwsElasticBlockStore

    @property
    def HostPath(self):
        """
        Gets the HostPath of this V1PersistentVolumeSpec.
        HostPath represents a directory on the host. Provisioned by a developer or tester. This is useful for single-node development and testing only! On-host storage is not supported in any way and WILL NOT WORK in a multi-node cluster. More info: http://releases.k8s.io/HEAD/docs/user-guide/volumes.md#hostpath

        :return: The HostPath of this V1PersistentVolumeSpec.
        :rtype: V1HostPathVolumeSource
        """
        return self._HostPath

    @HostPath.setter
    def HostPath(self, HostPath):
        """
        Sets the HostPath of this V1PersistentVolumeSpec.
        HostPath represents a directory on the host. Provisioned by a developer or tester. This is useful for single-node development and testing only! On-host storage is not supported in any way and WILL NOT WORK in a multi-node cluster. More info: http://releases.k8s.io/HEAD/docs/user-guide/volumes.md#hostpath

        :param HostPath: The HostPath of this V1PersistentVolumeSpec.
        :type: V1HostPathVolumeSource
        """

        self._HostPath = HostPath

    @property
    def Glusterfs(self):
        """
        Gets the Glusterfs of this V1PersistentVolumeSpec.
        Glusterfs represents a Glusterfs volume that is attached to a host and exposed to the pod. Provisioned by an admin. More info: http://releases.k8s.io/HEAD/examples/volumes/glusterfs/README.md

        :return: The Glusterfs of this V1PersistentVolumeSpec.
        :rtype: V1GlusterfsVolumeSource
        """
        return self._Glusterfs

    @Glusterfs.setter
    def Glusterfs(self, Glusterfs):
        """
        Sets the Glusterfs of this V1PersistentVolumeSpec.
        Glusterfs represents a Glusterfs volume that is attached to a host and exposed to the pod. Provisioned by an admin. More info: http://releases.k8s.io/HEAD/examples/volumes/glusterfs/README.md

        :param Glusterfs: The Glusterfs of this V1PersistentVolumeSpec.
        :type: V1GlusterfsVolumeSource
        """

        self._Glusterfs = Glusterfs

    @property
    def Nfs(self):
        """
        Gets the Nfs of this V1PersistentVolumeSpec.
        NFS represents an NFS mount on the host. Provisioned by an admin. More info: http://releases.k8s.io/HEAD/docs/user-guide/volumes.md#nfs

        :return: The Nfs of this V1PersistentVolumeSpec.
        :rtype: V1NFSVolumeSource
        """
        return self._Nfs

    @Nfs.setter
    def Nfs(self, Nfs):
        """
        Sets the Nfs of this V1PersistentVolumeSpec.
        NFS represents an NFS mount on the host. Provisioned by an admin. More info: http://releases.k8s.io/HEAD/docs/user-guide/volumes.md#nfs

        :param Nfs: The Nfs of this V1PersistentVolumeSpec.
        :type: V1NFSVolumeSource
        """

        self._Nfs = Nfs

    @property
    def Rbd(self):
        """
        Gets the Rbd of this V1PersistentVolumeSpec.
        RBD represents a Rados Block Device mount on the host that shares a pod's lifetime. More info: http://releases.k8s.io/HEAD/examples/volumes/rbd/README.md

        :return: The Rbd of this V1PersistentVolumeSpec.
        :rtype: V1RBDVolumeSource
        """
        return self._Rbd

    @Rbd.setter
    def Rbd(self, Rbd):
        """
        Sets the Rbd of this V1PersistentVolumeSpec.
        RBD represents a Rados Block Device mount on the host that shares a pod's lifetime. More info: http://releases.k8s.io/HEAD/examples/volumes/rbd/README.md

        :param Rbd: The Rbd of this V1PersistentVolumeSpec.
        :type: V1RBDVolumeSource
        """

        self._Rbd = Rbd

    @property
    def Iscsi(self):
        """
        Gets the Iscsi of this V1PersistentVolumeSpec.
        ISCSI represents an ISCSI Disk resource that is attached to a kubelet's host machine and then exposed to the pod. Provisioned by an admin.

        :return: The Iscsi of this V1PersistentVolumeSpec.
        :rtype: V1ISCSIVolumeSource
        """
        return self._Iscsi

    @Iscsi.setter
    def Iscsi(self, Iscsi):
        """
        Sets the Iscsi of this V1PersistentVolumeSpec.
        ISCSI represents an ISCSI Disk resource that is attached to a kubelet's host machine and then exposed to the pod. Provisioned by an admin.

        :param Iscsi: The Iscsi of this V1PersistentVolumeSpec.
        :type: V1ISCSIVolumeSource
        """

        self._Iscsi = Iscsi

    @property
    def Cinder(self):
        """
        Gets the Cinder of this V1PersistentVolumeSpec.
        Cinder represents a cinder volume attached and mounted on kubelets host machine More info: http://releases.k8s.io/HEAD/examples/mysql-cinder-pd/README.md

        :return: The Cinder of this V1PersistentVolumeSpec.
        :rtype: V1CinderVolumeSource
        """
        return self._Cinder

    @Cinder.setter
    def Cinder(self, Cinder):
        """
        Sets the Cinder of this V1PersistentVolumeSpec.
        Cinder represents a cinder volume attached and mounted on kubelets host machine More info: http://releases.k8s.io/HEAD/examples/mysql-cinder-pd/README.md

        :param Cinder: The Cinder of this V1PersistentVolumeSpec.
        :type: V1CinderVolumeSource
        """

        self._Cinder = Cinder

    @property
    def Cephfs(self):
        """
        Gets the Cephfs of this V1PersistentVolumeSpec.
        CephFS represents a Ceph FS mount on the host that shares a pod's lifetime

        :return: The Cephfs of this V1PersistentVolumeSpec.
        :rtype: V1CephFSVolumeSource
        """
        return self._Cephfs

    @Cephfs.setter
    def Cephfs(self, Cephfs):
        """
        Sets the Cephfs of this V1PersistentVolumeSpec.
        CephFS represents a Ceph FS mount on the host that shares a pod's lifetime

        :param Cephfs: The Cephfs of this V1PersistentVolumeSpec.
        :type: V1CephFSVolumeSource
        """

        self._Cephfs = Cephfs

    @property
    def Fc(self):
        """
        Gets the Fc of this V1PersistentVolumeSpec.
        FC represents a Fibre Channel resource that is attached to a kubelet's host machine and then exposed to the pod.

        :return: The Fc of this V1PersistentVolumeSpec.
        :rtype: V1FCVolumeSource
        """
        return self._Fc

    @Fc.setter
    def Fc(self, Fc):
        """
        Sets the Fc of this V1PersistentVolumeSpec.
        FC represents a Fibre Channel resource that is attached to a kubelet's host machine and then exposed to the pod.

        :param Fc: The Fc of this V1PersistentVolumeSpec.
        :type: V1FCVolumeSource
        """

        self._Fc = Fc

    @property
    def Flocker(self):
        """
        Gets the Flocker of this V1PersistentVolumeSpec.
        Flocker represents a Flocker volume attached to a kubelet's host machine and exposed to the pod for its usage. This depends on the Flocker control service being running

        :return: The Flocker of this V1PersistentVolumeSpec.
        :rtype: V1FlockerVolumeSource
        """
        return self._Flocker

    @Flocker.setter
    def Flocker(self, Flocker):
        """
        Sets the Flocker of this V1PersistentVolumeSpec.
        Flocker represents a Flocker volume attached to a kubelet's host machine and exposed to the pod for its usage. This depends on the Flocker control service being running

        :param Flocker: The Flocker of this V1PersistentVolumeSpec.
        :type: V1FlockerVolumeSource
        """

        self._Flocker = Flocker

    @property
    def FlexVolume(self):
        """
        Gets the FlexVolume of this V1PersistentVolumeSpec.
        FlexVolume represents a generic volume resource that is provisioned/attached using a exec based plugin. This is an alpha feature and may change in future.

        :return: The FlexVolume of this V1PersistentVolumeSpec.
        :rtype: V1FlexVolumeSource
        """
        return self._FlexVolume

    @FlexVolume.setter
    def FlexVolume(self, FlexVolume):
        """
        Sets the FlexVolume of this V1PersistentVolumeSpec.
        FlexVolume represents a generic volume resource that is provisioned/attached using a exec based plugin. This is an alpha feature and may change in future.

        :param FlexVolume: The FlexVolume of this V1PersistentVolumeSpec.
        :type: V1FlexVolumeSource
        """

        self._FlexVolume = FlexVolume

    @property
    def AzureFile(self):
        """
        Gets the AzureFile of this V1PersistentVolumeSpec.
        AzureFile represents an Azure File Service mount on the host and bind mount to the pod.

        :return: The AzureFile of this V1PersistentVolumeSpec.
        :rtype: V1AzureFileVolumeSource
        """
        return self._AzureFile

    @AzureFile.setter
    def AzureFile(self, AzureFile):
        """
        Sets the AzureFile of this V1PersistentVolumeSpec.
        AzureFile represents an Azure File Service mount on the host and bind mount to the pod.

        :param AzureFile: The AzureFile of this V1PersistentVolumeSpec.
        :type: V1AzureFileVolumeSource
        """

        self._AzureFile = AzureFile

    @property
    def VsphereVolume(self):
        """
        Gets the VsphereVolume of this V1PersistentVolumeSpec.
        VsphereVolume represents a vSphere volume attached and mounted on kubelets host machine

        :return: The VsphereVolume of this V1PersistentVolumeSpec.
        :rtype: V1VsphereVirtualDiskVolumeSource
        """
        return self._VsphereVolume

    @VsphereVolume.setter
    def VsphereVolume(self, VsphereVolume):
        """
        Sets the VsphereVolume of this V1PersistentVolumeSpec.
        VsphereVolume represents a vSphere volume attached and mounted on kubelets host machine

        :param VsphereVolume: The VsphereVolume of this V1PersistentVolumeSpec.
        :type: V1VsphereVirtualDiskVolumeSource
        """

        self._VsphereVolume = VsphereVolume

    @property
    def AccessModes(self):
        """
        Gets the AccessModes of this V1PersistentVolumeSpec.
        AccessModes contains all ways the volume can be mounted. More info: http://releases.k8s.io/HEAD/docs/user-guide/persistent-volumes.md#access-modes

        :return: The AccessModes of this V1PersistentVolumeSpec.
        :rtype: list[V1PersistentVolumeAccessMode]
        """
        return self._AccessModes

    @AccessModes.setter
    def AccessModes(self, AccessModes):
        """
        Sets the AccessModes of this V1PersistentVolumeSpec.
        AccessModes contains all ways the volume can be mounted. More info: http://releases.k8s.io/HEAD/docs/user-guide/persistent-volumes.md#access-modes

        :param AccessModes: The AccessModes of this V1PersistentVolumeSpec.
        :type: list[V1PersistentVolumeAccessMode]
        """

        self._AccessModes = AccessModes

    @property
    def ClaimRef(self):
        """
        Gets the ClaimRef of this V1PersistentVolumeSpec.
        ClaimRef is part of a bi-directional binding between PersistentVolume and PersistentVolumeClaim. Expected to be non-nil when bound. claim.VolumeName is the authoritative bind between PV and PVC. More info: http://releases.k8s.io/HEAD/docs/user-guide/persistent-volumes.md#binding

        :return: The ClaimRef of this V1PersistentVolumeSpec.
        :rtype: V1ObjectReference
        """
        return self._ClaimRef

    @ClaimRef.setter
    def ClaimRef(self, ClaimRef):
        """
        Sets the ClaimRef of this V1PersistentVolumeSpec.
        ClaimRef is part of a bi-directional binding between PersistentVolume and PersistentVolumeClaim. Expected to be non-nil when bound. claim.VolumeName is the authoritative bind between PV and PVC. More info: http://releases.k8s.io/HEAD/docs/user-guide/persistent-volumes.md#binding

        :param ClaimRef: The ClaimRef of this V1PersistentVolumeSpec.
        :type: V1ObjectReference
        """

        self._ClaimRef = ClaimRef

    @property
    def PersistentVolumeReclaimPolicy(self):
        """
        Gets the PersistentVolumeReclaimPolicy of this V1PersistentVolumeSpec.
        What happens to a persistent volume when released from its claim. Valid options are Retain (default) and Recycle. Recyling must be supported by the volume plugin underlying this persistent volume. More info: http://releases.k8s.io/HEAD/docs/user-guide/persistent-volumes.md#recycling-policy

        :return: The PersistentVolumeReclaimPolicy of this V1PersistentVolumeSpec.
        :rtype: str
        """
        return self._PersistentVolumeReclaimPolicy

    @PersistentVolumeReclaimPolicy.setter
    def PersistentVolumeReclaimPolicy(self, PersistentVolumeReclaimPolicy):
        """
        Sets the PersistentVolumeReclaimPolicy of this V1PersistentVolumeSpec.
        What happens to a persistent volume when released from its claim. Valid options are Retain (default) and Recycle. Recyling must be supported by the volume plugin underlying this persistent volume. More info: http://releases.k8s.io/HEAD/docs/user-guide/persistent-volumes.md#recycling-policy

        :param PersistentVolumeReclaimPolicy: The PersistentVolumeReclaimPolicy of this V1PersistentVolumeSpec.
        :type: str
        """

        self._PersistentVolumeReclaimPolicy = PersistentVolumeReclaimPolicy

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
