# coding: utf-8

"""

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class V1PodStatus(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, Phase=None, Conditions=None, Message=None, Reason=None, HostIP=None, PodIP=None, StartTime=None, ContainerStatuses=None):
        """
        V1PodStatus - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'Phase': 'str',
            'Conditions': 'list[V1PodCondition]',
            'Message': 'str',
            'Reason': 'str',
            'HostIP': 'str',
            'PodIP': 'str',
            'StartTime': 'datetime',
            'ContainerStatuses': 'list[V1ContainerStatus]'
        }

        self.attribute_map = {
            'Phase': 'phase',
            'Conditions': 'conditions',
            'Message': 'message',
            'Reason': 'reason',
            'HostIP': 'hostIP',
            'PodIP': 'podIP',
            'StartTime': 'startTime',
            'ContainerStatuses': 'containerStatuses'
        }

        self._Phase = Phase
        self._Conditions = Conditions
        self._Message = Message
        self._Reason = Reason
        self._HostIP = HostIP
        self._PodIP = PodIP
        self._StartTime = StartTime
        self._ContainerStatuses = ContainerStatuses

    @property
    def Phase(self):
        """
        Gets the Phase of this V1PodStatus.
        Current condition of the pod. More info: http://releases.k8s.io/HEAD/docs/user-guide/pod-states.md#pod-phase

        :return: The Phase of this V1PodStatus.
        :rtype: str
        """
        return self._Phase

    @Phase.setter
    def Phase(self, Phase):
        """
        Sets the Phase of this V1PodStatus.
        Current condition of the pod. More info: http://releases.k8s.io/HEAD/docs/user-guide/pod-states.md#pod-phase

        :param Phase: The Phase of this V1PodStatus.
        :type: str
        """

        self._Phase = Phase

    @property
    def Conditions(self):
        """
        Gets the Conditions of this V1PodStatus.
        Current service state of pod. More info: http://releases.k8s.io/HEAD/docs/user-guide/pod-states.md#pod-conditions

        :return: The Conditions of this V1PodStatus.
        :rtype: list[V1PodCondition]
        """
        return self._Conditions

    @Conditions.setter
    def Conditions(self, Conditions):
        """
        Sets the Conditions of this V1PodStatus.
        Current service state of pod. More info: http://releases.k8s.io/HEAD/docs/user-guide/pod-states.md#pod-conditions

        :param Conditions: The Conditions of this V1PodStatus.
        :type: list[V1PodCondition]
        """

        self._Conditions = Conditions

    @property
    def Message(self):
        """
        Gets the Message of this V1PodStatus.
        A human readable message indicating details about why the pod is in this condition.

        :return: The Message of this V1PodStatus.
        :rtype: str
        """
        return self._Message

    @Message.setter
    def Message(self, Message):
        """
        Sets the Message of this V1PodStatus.
        A human readable message indicating details about why the pod is in this condition.

        :param Message: The Message of this V1PodStatus.
        :type: str
        """

        self._Message = Message

    @property
    def Reason(self):
        """
        Gets the Reason of this V1PodStatus.
        A brief CamelCase message indicating details about why the pod is in this state. e.g. 'OutOfDisk'

        :return: The Reason of this V1PodStatus.
        :rtype: str
        """
        return self._Reason

    @Reason.setter
    def Reason(self, Reason):
        """
        Sets the Reason of this V1PodStatus.
        A brief CamelCase message indicating details about why the pod is in this state. e.g. 'OutOfDisk'

        :param Reason: The Reason of this V1PodStatus.
        :type: str
        """

        self._Reason = Reason

    @property
    def HostIP(self):
        """
        Gets the HostIP of this V1PodStatus.
        IP address of the host to which the pod is assigned. Empty if not yet scheduled.

        :return: The HostIP of this V1PodStatus.
        :rtype: str
        """
        return self._HostIP

    @HostIP.setter
    def HostIP(self, HostIP):
        """
        Sets the HostIP of this V1PodStatus.
        IP address of the host to which the pod is assigned. Empty if not yet scheduled.

        :param HostIP: The HostIP of this V1PodStatus.
        :type: str
        """

        self._HostIP = HostIP

    @property
    def PodIP(self):
        """
        Gets the PodIP of this V1PodStatus.
        IP address allocated to the pod. Routable at least within the cluster. Empty if not yet allocated.

        :return: The PodIP of this V1PodStatus.
        :rtype: str
        """
        return self._PodIP

    @PodIP.setter
    def PodIP(self, PodIP):
        """
        Sets the PodIP of this V1PodStatus.
        IP address allocated to the pod. Routable at least within the cluster. Empty if not yet allocated.

        :param PodIP: The PodIP of this V1PodStatus.
        :type: str
        """

        self._PodIP = PodIP

    @property
    def StartTime(self):
        """
        Gets the StartTime of this V1PodStatus.
        RFC 3339 date and time at which the object was acknowledged by the Kubelet. This is before the Kubelet pulled the container image(s) for the pod.

        :return: The StartTime of this V1PodStatus.
        :rtype: datetime
        """
        return self._StartTime

    @StartTime.setter
    def StartTime(self, StartTime):
        """
        Sets the StartTime of this V1PodStatus.
        RFC 3339 date and time at which the object was acknowledged by the Kubelet. This is before the Kubelet pulled the container image(s) for the pod.

        :param StartTime: The StartTime of this V1PodStatus.
        :type: datetime
        """

        self._StartTime = StartTime

    @property
    def ContainerStatuses(self):
        """
        Gets the ContainerStatuses of this V1PodStatus.
        The list has one entry per container in the manifest. Each entry is currently the output of `docker inspect`. More info: http://releases.k8s.io/HEAD/docs/user-guide/pod-states.md#container-statuses

        :return: The ContainerStatuses of this V1PodStatus.
        :rtype: list[V1ContainerStatus]
        """
        return self._ContainerStatuses

    @ContainerStatuses.setter
    def ContainerStatuses(self, ContainerStatuses):
        """
        Sets the ContainerStatuses of this V1PodStatus.
        The list has one entry per container in the manifest. Each entry is currently the output of `docker inspect`. More info: http://releases.k8s.io/HEAD/docs/user-guide/pod-states.md#container-statuses

        :param ContainerStatuses: The ContainerStatuses of this V1PodStatus.
        :type: list[V1ContainerStatus]
        """

        self._ContainerStatuses = ContainerStatuses

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
