# coding: utf-8

"""

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class V1ResourceQuotaSpec(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, Hard=None, Scopes=None):
        """
        V1ResourceQuotaSpec - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'Hard': 'object',
            'Scopes': 'list[V1ResourceQuotaScope]'
        }

        self.attribute_map = {
            'Hard': 'hard',
            'Scopes': 'scopes'
        }

        self._Hard = Hard
        self._Scopes = Scopes

    @property
    def Hard(self):
        """
        Gets the Hard of this V1ResourceQuotaSpec.
        Hard is the set of desired hard limits for each named resource. More info: http://releases.k8s.io/HEAD/docs/design/admission_control_resource_quota.md#admissioncontrol-plugin-resourcequota

        :return: The Hard of this V1ResourceQuotaSpec.
        :rtype: object
        """
        return self._Hard

    @Hard.setter
    def Hard(self, Hard):
        """
        Sets the Hard of this V1ResourceQuotaSpec.
        Hard is the set of desired hard limits for each named resource. More info: http://releases.k8s.io/HEAD/docs/design/admission_control_resource_quota.md#admissioncontrol-plugin-resourcequota

        :param Hard: The Hard of this V1ResourceQuotaSpec.
        :type: object
        """

        self._Hard = Hard

    @property
    def Scopes(self):
        """
        Gets the Scopes of this V1ResourceQuotaSpec.
        A collection of filters that must match each object tracked by a quota. If not specified, the quota matches all objects.

        :return: The Scopes of this V1ResourceQuotaSpec.
        :rtype: list[V1ResourceQuotaScope]
        """
        return self._Scopes

    @Scopes.setter
    def Scopes(self, Scopes):
        """
        Sets the Scopes of this V1ResourceQuotaSpec.
        A collection of filters that must match each object tracked by a quota. If not specified, the quota matches all objects.

        :param Scopes: The Scopes of this V1ResourceQuotaSpec.
        :type: list[V1ResourceQuotaScope]
        """

        self._Scopes = Scopes

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
